### ISSUE TITLE
Unable to compile on Arch Linux

### ISSUE THREAD

**Issue by tmose1106** [KeepPositive/TAD-DG#1]
So, I'm trying to compile this thing on my Arch Linux install using `OpenJDK8`, and I get the errors shown in the picture below. I don't really know anything about Java, so maybe you can find out what this means... _Maybe._ 

For this game to fit anywhere in the Linux world, you are going to need to get this **worked out!**

![1464121665](https://cloud.githubusercontent.com/assets/15310560/15518819/a41b0cd6-21cc-11e6-8863-05d2057e6fba.png)

**Comment by ghost** [comment]
I complied them as class files, see if that works
